name: Kittygram CI/CD Workflow
description: Автоматическое тестирование и деплой Kittygram
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
  build-and-push:
    needs: test
    runs-on: ubuntu-latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
  post-deploy-test:
    needs: deploy
    runs-on: ubuntu-latest
  notify:
    needs: post-deploy-test
    runs-on: ubuntu-latest
