upstream backend {
    server backend:8000;
}

server {
    listen 80;
    index index.html;

    # API запросы -> отправляем на бэкенд
    location /api/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Админка Django -> отправляем на бэкенд
    location /admin/ {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Статика (CSS, JS, картинки интерфейса)
    location /static/ {
        alias /staticfiles/;
    }

    # Медиа (фото котиков, загруженные пользователями)
    location /media/ {
        alias /media_files/;
    }

    # Фронтенд (React приложение)
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
